//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Sirket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departman
    {
        public int DepartmanID { get; set; }
        public string DepartmanAdi { get; set; }
        public Nullable<int> ElemanSayisi { get; set; }
        public Nullable<int> ProjeSayisi { get; set; }
        public Nullable<int> Butce { get; set; }
    }
}
