//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Sirket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SirketEntities : DbContext
    {
        public SirketEntities()
            : base("name=SirketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Calisanlar> Calisanlar { get; set; }
        public virtual DbSet<Departman> Departman { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Program> Program { get; set; }
        public virtual DbSet<Musteriler> Musteriler { get; set; }
    }
}
