//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Sirket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int MusteriID { get; set; }
        public string MusteriAdi { get; set; }
        public string AldigiHizmet { get; set; }
        public Nullable<int> Fiyat { get; set; }
        public Nullable<System.DateTime> AldigiTarih { get; set; }
    }
}
