//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_Sirket
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public int ProgramID { get; set; }
        public string ProgramAdi { get; set; }
        public Nullable<int> YapilanProjeSayisi { get; set; }
        public Nullable<int> KullanilanDepartmanSayisi { get; set; }
        public Nullable<System.DateTime> BaslangicTarihi { get; set; }
    }
}
